#!/bin/sh

# Find out script's dir, resolving any links to the script itself
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ] ; do SOURCE="$(readlink "$SOURCE")"; done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

cd $DIR/../src
if [[ ! -z `ls *.o[0-9] 2> /dev/null` ]]; then rm *.o[0-9]; fi
gsc -e '(compile-file "cairo" cc-options: "-w -I/usr/include/cairo -I/usr/include/freetype2" ld-options: "-lcairo")'
